MDBoxLayout:
    orientation: "vertical"

    MDTabs:
        id:TopTabs
        Tab:
            title: "Monitor"
            icon: "monitor"

            MDTabs:
                id:MonitorTabs

                Tab:
                    icon:"speedometer"
                    title:"Pressure"

                    MDBoxLayout:
                        orientation:'horizontal'

                        MDBoxLayout:
                            orientation:"vertical"

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-1-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 1'

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-2-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 2'

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-3-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 3'

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-4-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 4'

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-5-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 5'

                            MDBoxLayout:
                                orientation:'horizontal'

                                MDIconButton:
                                    icon:"numeric-6-box"
                                    pos_hint:{"center_x":0.5,"center_y":0.5}
                                MDLabel:
                                    text:'Pressure 6'

                        PressureGraph:
                            id:PressureGraph
                Tab:
                    icon:"approximately-equal"
                    title:"Flow"
                Tab:
                    icon:"thermometer"
                    title:"Temperature"
